var currentUser=null,currentUserData=null;
setTimeout(function(){document.getElementById('splashScreen').classList.add('hidden');auth.onAuthStateChanged(function(user){if(user){currentUser=user;db.collection('users').doc(user.uid).get().then(function(doc){if(doc.exists&&doc.data().name){currentUserData=doc.data();}else{currentUserData={uid:user.uid,name:'User',username:'@user',bio:'',avatar:'',followers:[],following:[],blockedUsers:[],achievements:[],streak:0,bestStreak:0,xp:0,coins:0,level:{current:1,title:'Explorer',progress:0},stats:{achievements:0,totalMessages:0},inventory:[],lastDailyReward:null,rewardStreak:0};}showApp();updateStreak();}).catch(function(){currentUserData={name:'User',username:'@user',bio:'',avatar:'',followers:[],following:[],level:{current:1,title:'Explorer',progress:0},stats:{achievements:0},coins:0,inventory:[]};showApp();});}else{showLogin();}});},2500);
function showApp(){document.getElementById('authScreen').classList.remove('show');document.getElementById('mainApp').classList.add('show');document.querySelectorAll('.nav-btn').forEach(function(b){b.addEventListener('click',function(){navigate(this.dataset.page);});});navigate('home');if(currentUser){db.collection('users').doc(currentUser.uid).update({onlineStatus:'online'});}window.addEventListener('beforeunload',function(){if(currentUser){db.collection('users').doc(currentUser.uid).update({onlineStatus:'offline',lastSeen:firebase.firestore.FieldValue.serverTimestamp()});}});}
function navigate(p){document.querySelectorAll('.nav-btn').forEach(function(b){b.classList.remove('active');});var btn=document.querySelector('[data-page="'+p+'"]');if(btn)btn.classList.add('active');var c=document.getElementById('contentArea');if(p==='home')renderHome(c);if(p==='chats')renderChats(c);if(p==='search')renderSearch(c);if(p==='games')openGames();if(p==='profile')renderProfile(c);}
function updateStreak(){if(!currentUser)return;var ref=db.collection('users').doc(currentUser.uid);ref.get().then(function(doc){var d=doc.data();var today=new Date();today.setHours(0,0,0,0);var last=d.lastActive?d.lastActive.toDate():null;var s=d.streak||0;if(last){last.setHours(0,0,0,0);var diff=(today-last)/86400000;if(diff===1)s++;else if(diff>1)s=1;}else{s=1;}ref.update({streak:s,lastActive:firebase.firestore.FieldValue.serverTimestamp(),bestStreak:Math.max(s,d.bestStreak||0)});currentUserData.streak=s;currentUserData.bestStreak=Math.max(s,d.bestStreak||0);});}

function renderHome(c){var u=currentUserData;var name=(u.name&&u.name!=='undefined')?u.name:'User';var today=new Date().toDateString();var lastReward=u.lastDailyReward?new Date(u.lastDailyReward).toDateString():'';var canClaim=today!==lastReward;var streak=u.rewardStreak||0;if(!lastReward||new Date()-new Date(u.lastDailyReward)>172800000){streak=0;}var rewards=[20,20,40,40,50,50,190];var todayReward=rewards[Math.min(streak,6)];
c.innerHTML='<div class="card" style="text-align:center"><div style="font-size:60px">🕷️</div><h1 style="color:var(--gold);font-size:26px;font-weight:900;letter-spacing:3px">ChronoX</h1><p style="color:rgba(255,255,255,0.6)">Welcome, '+name+'</p></div>'+
'<div class="card" style="background:linear-gradient(135deg,rgba(212,175,55,0.15),rgba(0,212,255,0.08));border:1px solid #D4AF37;text-align:center"><h3 style="color:#D4AF37;margin-bottom:8px">🎁 Daily Reward</h3><p style="color:rgba(255,255,255,0.6);font-size:12px;margin-bottom:10px">Day '+(streak+1)+' of 7</p><div style="font-size:35px;margin:10px 0">💰 <b style="color:#D4AF37">'+todayReward+'</b></div>'+(canClaim?'<button class="btn" onclick="claimDailyReward()" style="margin-top:8px">Claim Reward 🎁</button>':'<p style="color:#2ED573;font-size:12px">✅ Claimed! Come back tomorrow!</p>')+'<div style="display:flex;justify-content:center;gap:8px;margin-top:10px">'+rewards.map(function(r,i){var claimed=i<streak;var isToday=i===streak&&canClaim;return'<div style="text-align:center;padding:6px 8px;border-radius:8px;background:'+(claimed?'rgba(46,213,115,0.2)':isToday?'rgba(212,175,55,0.3)':'rgba(255,255,255,0.05)')+';border:1px solid '+(isToday?'#D4AF37':'rgba(255,255,255,0.1)')+'"><small style="color:rgba(255,255,255,0.5)">Day'+(i+1)+'</small><br><b style="color:'+(claimed?'#2ED573':'#D4AF37')+'">'+r+'</b></div>';}).join('')+'</div></div>'+
'<div class="card" style="display:flex;align-items:center;gap:15px"><span style="font-size:45px">🔥</span><div><h1 style="color:var(--gold)">'+(u.streak||0)+' Days</h1><small style="color:rgba(255,255,255,0.6)">Streak</small></div></div>'+
'<div class="card"><div style="display:flex;justify-content:space-around;text-align:center"><div><h2 style="color:var(--gold)">'+(u.coins||0)+'</h2><small>💰 Coins</small></div><div><h2 style="color:#00D4FF">'+(u.xp||0)+'</h2><small>⚡ XP</small></div><div><h2 style="color:#2ED573">'+(u.stats?.achievements||0)+'</h2><small>🏆</small></div></div></div>';}

function claimDailyReward(){var u=currentUserData;var today=new Date().toDateString();var lastReward=u.lastDailyReward?new Date(u.lastDailyReward).toDateString():'';if(today===lastReward){showToast('Already claimed!','error');return;}var streak=u.rewardStreak||0;if(lastReward&&new Date()-new Date(u.lastDailyReward)>172800000){streak=0;}var rewards=[20,20,40,40,50,50,190];var todayReward=rewards[Math.min(streak,6)];db.collection('users').doc(currentUser.uid).update({coins:firebase.firestore.FieldValue.increment(todayReward),lastDailyReward:firebase.firestore.FieldValue.serverTimestamp(),rewardStreak:streak+1}).then(function(){currentUserData.coins=(currentUserData.coins||0)+todayReward;currentUserData.lastDailyReward=new Date().toISOString();currentUserData.rewardStreak=streak+1;showToast('🎁 +'+todayReward+' coins!');navigate('home');});}
console.log('✅ App loaded');
