var chatId=null,chatUser=null,chatListener=null,activeTab='chats';
function renderChats(c){c.innerHTML='<h2 style="color:#D4AF37;margin-bottom:10px">💬 Messages</h2><div style="display:flex;gap:5px;margin-bottom:12px"><button id="tabChats" class="btn-out" style="flex:1;background:rgba(212,175,55,0.2)" onclick="switchTab(\'chats\')">💬 Chats</button><button id="tabRequests" class="btn-out" style="flex:1" onclick="switchTab(\'requests\')">📩 Requests</button></div><div id="chatListContainer"></div>';loadChatList();}
function switchTab(tab){activeTab=tab;document.getElementById('tabChats').style.background=tab==='chats'?'rgba(212,175,55,0.2)':'';document.getElementById('tabRequests').style.background=tab==='requests'?'rgba(212,175,55,0.2)':'';loadChatList();}
function loadChatList(){var c=document.getElementById('chatListContainer');if(!c)return;c.innerHTML='<p style="text-align:center;color:rgba(255,255,255,0.5);padding:20px">Loading...</p>';if(activeTab==='requests'){c.innerHTML='<p style="text-align:center;color:rgba(255,255,255,0.5);padding:30px">No pending requests</p>';return;}
var mutualIds=(currentUserData.following||[]).filter(function(id){return (currentUserData.followers||[]).indexOf(id)!==-1;});
db.collection('chats').where('participants','array-contains',currentUser.uid).get().then(function(snap){var chatMap={};snap.forEach(function(doc){var chat=doc.data();var oid=chat.participants.find(function(id){return id!==currentUser.uid;});if(!oid||['annaya_ai','tarun_ai','chronox_ai'].includes(oid))return;chatMap[oid]={chatId:doc.id,lastMsg:chat.lastMessage||'',time:chat.lastMessageTime};});mutualIds.forEach(function(id){if(!chatMap[id])chatMap[id]={chatId:null,lastMsg:'',time:null};});var ids=Object.keys(chatMap);if(ids.length===0){c.innerHTML='<p style="text-align:center;color:rgba(255,255,255,0.5);padding:30px">No chats yet</p>';return;}
var promises=ids.map(function(uid){return db.collection('users').doc(uid).get().then(function(ud){var u=ud.data();if(!u)return null;if((currentUserData.blockedUsers||[]).indexOf(uid)!==-1)return null;if((u.blockedUsers||[]).indexOf(currentUser.uid)!==-1)return null;var info=chatMap[uid];return{chatId:info.chatId||('new_'+[currentUser.uid,uid].sort().join('_')),userId:uid,name:u.name,avatar:u.avatar||'',lastMsg:info.lastMsg||'Tap to chat',time:info.time?formatTime(info.time.toDate()):'',isOnline:u.onlineStatus==='online',lastSeen:u.lastSeen?u.lastSeen.toDate():null};});});
Promise.all(promises).then(function(results){var users=results.filter(function(r){return r!==null;});if(users.length===0){c.innerHTML='<p style="text-align:center;color:rgba(255,255,255,0.5);padding:30px">No chats yet</p>';return;}users.sort(function(a,b){if(a.isOnline&&!b.isOnline)return-1;if(!a.isOnline&&b.isOnline)return 1;return a.name.localeCompare(b.name);});var h='';users.forEach(function(u){var st=u.isOnline?'● Online':getLastSeenText(u.lastSeen);var sc=u.isOnline?'#2ED573':'#888';h+='<div class="chat-item" onclick="openChatWindow(\''+u.chatId+'\',\''+u.userId+'\',\''+u.name+'\',\''+u.avatar+'\',false)" style="display:flex;align-items:center;padding:14px;background:rgba(19,24,66,0.7);border:1px solid rgba(212,175,55,0.15);border-radius:14px;cursor:pointer;gap:12px;margin-bottom:6px"><div style="position:relative;flex-shrink:0"><img src="'+(u.avatar||defaultAvatar(u.name))+'" style="width:52px;height:52px;border-radius:50%;border:2px solid #D4AF37;object-fit:cover" onerror="this.src=\''+defaultAvatar(u.name)+'\'"><span style="position:absolute;bottom:2px;right:2px;width:12px;height:12px;background:'+sc+';border-radius:50%;border:2px solid #0A0E27"></span></div><div style="flex:1;min-width:0"><b>'+u.name+'</b><br><small style="color:rgba(255,255,255,0.5);display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+u.lastMsg+'</small></div><div style="text-align:right;flex-shrink:0"><small style="color:'+sc+';font-size:11px">'+st+'</small><br><small style="color:#D4AF37;font-size:10px">'+u.time+'</small></div></div>';});c.innerHTML=h;});});}
function openChatWindow(cid,uid,name,avt,ai){chatId=cid;chatUser={uid:uid,name:name,avt:avt,ai:false};document.getElementById('chatWindow').classList.add('show');document.getElementById('chatName').textContent=name;document.getElementById('chatMessages').innerHTML='';document.getElementById('msgInput').value='';setTimeout(function(){document.getElementById('msgInput').focus();},300);document.getElementById('chatAvatarEmoji').style.display='none';document.getElementById('chatAvatar').style.display='inline';document.getElementById('chatAvatar').src=avt||defaultAvatar(name);if(chatListener)chatListener();chatListener=db.collection('chats').doc(cid).collection('messages').orderBy('timestamp','asc').onSnapshot(function(snap){var mc=document.getElementById('chatMessages');if(!mc)return;mc.innerHTML='';snap.forEach(function(doc){var m=doc.data(),sent=m.senderId===currentUser.uid;mc.innerHTML+='<div class="'+(sent?'msg-sent':'msg-rec')+'">'+(m.mediaUrl?'<img src="'+m.mediaUrl+'" style="max-width:180px;border-radius:10px;margin-bottom:4px">':'')+m.text+'<div style="margin-top:3px"><small style="opacity:0.7;font-size:10px">'+(m.timestamp?formatTime(m.timestamp.toDate()):'')+'</small>'+(sent?'<small style="font-size:10px;color:rgba(255,255,255,0.4);margin-left:8px">'+(m.seen?'✓✓ Seen':'✓ Sent')+'</small>':'')+'</div></div>';});mc.scrollTop=mc.scrollHeight;});}
function closeChat(){document.getElementById('chatWindow').classList.remove('show');if(chatListener)chatListener();chatListener=null;chatId=null;chatUser=null;}
function sendMessage(){var input=document.getElementById('msgInput');if(!input)return;var t=input.value.trim();if(!t||!chatId||!chatUser)return;if(chatId.startsWith('new_')){var ref=db.collection('chats').doc();ref.set({participants:[currentUser.uid,chatUser.uid],lastMessage:t,lastMessageTime:firebase.firestore.FieldValue.serverTimestamp()}).then(function(){chatId=ref.id;ref.collection('messages').add({senderId:currentUser.uid,text:t,timestamp:firebase.firestore.FieldValue.serverTimestamp(),seen:false});input.value='';input.focus();loadChatList();});return;}db.collection('chats').doc(chatId).collection('messages').add({senderId:currentUser.uid,text:t,timestamp:firebase.firestore.FieldValue.serverTimestamp(),seen:false});db.collection('chats').doc(chatId).set({participants:[currentUser.uid,chatUser.uid],lastMessage:t,lastMessageTime:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});input.value='';input.focus();}
function getLastSeenText(ls){if(!ls)return'Offline';var d=Date.now()-ls,m=Math.floor(d/60000),h=Math.floor(d/3600000);if(m<1)return'Just now';if(m<60)return m+'m ago';if(h<24)return h+'h ago';return ls.toLocaleDateString('en-IN',{day:'numeric',month:'short'});}
function attachMedia(){var inp=document.createElement('input');inp.type='file';inp.accept='image/*';inp.onchange=function(){var f=inp.files[0];if(!f||!chatId)return;var r=new FileReader();r.onload=function(e){db.collection('chats').doc(chatId).collection('messages').add({senderId:currentUser.uid,text:'📷 Photo',mediaUrl:e.target.result,timestamp:firebase.firestore.FieldValue.serverTimestamp(),seen:false});db.collection('chats').doc(chatId).set({lastMessage:'📷 Photo',lastMessageTime:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});};r.readAsDataURL(f);};inp.click();}
document.addEventListener('keydown',function(e){if(e.key==='Enter'&&!e.shiftKey){var w=document.getElementById('chatWindow');if(w&&w.classList.contains('show')){e.preventDefault();sendMessage();}}});
document.addEventListener('click',function(e){if(e.target.classList.contains('modal'))e.target.classList.remove('show');});
