var breakoutData;
function startBreakout(){openGameScreen('🧱 Breakout');gameCanvas.style.display='block';breakoutData={paddle:{x:gameCanvas.width/2-65,y:gameCanvas.height-42,w:130,h:15},ball:{x:gameCanvas.width/2,y:gameCanvas.height-70,dx:5,dy:-5,r:9},bricks:[],score:0,lives:3,level:1,particles:[],powerUps:[],combo:0,highScore:0};breakoutData.highScore=parseInt(localStorage.getItem('breakoutHigh')||'0');spawnBreakoutBricks();currentGameRestart=startBreakout;gameAnimation=requestAnimationFrame(breakoutLoop);}
function spawnBreakoutBricks(){breakoutData.bricks=[];var colors=['#FF4757','#FF6B81','#FFA502','#2ED573','#1E90FF','#7C3AED','#FFD700','#FF69B4'];var rows=4+breakoutData.level;for(var r=0;r<rows;r++)for(var c=0;c<9;c++)breakoutData.bricks.push({x:c*53+15,y:r*26+45,w:48,h:22,alive:true,color:colors[r%colors.length],hp:r<3?1:2,points:(rows-r)*5});}
function breakoutLoop(){if(!gameActive)return;var c=gameCanvas,ctx=gameCtx,p=breakoutData.paddle,b=breakoutData.ball,d=breakoutData;
var bgGrad=ctx.createLinearGradient(0,0,0,c.height);bgGrad.addColorStop(0,'#1a1a3e');bgGrad.addColorStop(1,'#0A0E27');ctx.fillStyle=bgGrad;ctx.fillRect(0,0,c.width,c.height);
b.x+=b.dx;b.y+=b.dy;if(b.x-b.r<=0||b.x+b.r>=c.width)b.dx*=-1;if(b.y-b.r<=0)b.dy*=-1;
if(b.y+b.r>=c.height){d.lives--;d.combo=0;if(d.lives<=0){if(d.score>d.highScore){d.highScore=d.score;localStorage.setItem('breakoutHigh',d.highScore);}endGame('🧱 Score: '+d.score+' | Best: '+d.highScore);return;}b.x=c.width/2;b.y=c.height-70;b.dx=5;b.dy=-5;}
if(b.y+b.r>=p.y&&b.x>p.x&&b.x<p.x+p.w){var hit=(b.x-p.x)/p.w;b.dy=-Math.abs(b.dy);b.dx=Math.sin((hit-0.5)*1.3)*6;d.combo++;if(d.combo>1)updateGameScore(d.combo*2);for(var i=0;i<6;i++)spawnBParticles(b.x,b.y,'#D4AF37');}
d.bricks.forEach(function(br){if(!br.alive)return;if(b.x+b.r>br.x&&b.x-b.r<br.x+br.w&&b.y+b.r>br.y&&b.y-b.r<br.y+br.h){b.dy*=-1;br.hp--;if(br.hp<=0){br.alive=false;d.score+=br.points;updateGameScore(d.score);for(var i=0;i<10;i++)spawnBParticles(br.x+br.w/2,br.y+br.h/2,br.color);}else{for(var i=0;i<4;i++)spawnBParticles(b.x,b.y,br.color);}}});
d.bricks.forEach(function(br){if(!br.alive)return;var bg=ctx.createLinearGradient(br.x,br.y,br.x,br.y+br.h);bg.addColorStop(0,br.color);bg.addColorStop(1,'rgba(0,0,0,0.3)');ctx.fillStyle=bg;ctx.shadowColor=br.color;ctx.shadowBlur=6;ctx.beginPath();ctx.roundRect(br.x,br.y,br.w,br.h,4);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='rgba(255,255,255,0.25)';ctx.fillRect(br.x,br.y,br.w,5);if(br.hp===2){ctx.strokeStyle='rgba(255,255,255,0.5)';ctx.lineWidth=1.5;ctx.strokeRect(br.x+3,br.y+3,br.w-6,br.h-6);}});
var pg=ctx.createLinearGradient(p.x,p.y,p.x,p.y+p.h);pg.addColorStop(0,'#D4AF37');pg.addColorStop(0.5,'#F5E6A3');pg.addColorStop(1,'#B8941F');ctx.fillStyle=pg;ctx.shadowColor='#D4AF37';ctx.shadowBlur=18;ctx.beginPath();ctx.roundRect(p.x,p.y,p.w,p.h,10);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,255,255,0.4)';ctx.lineWidth=2;ctx.stroke();
var ballGlow=ctx.createRadialGradient(b.x,b.y,0,b.x,b.y,b.r*3);ballGlow.addColorStop(0,'rgba(255,255,255,0.9)');ballGlow.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=ballGlow;ctx.beginPath();ctx.arc(b.x,b.y,b.r*3,0,Math.PI*2);ctx.fill();var ballGrad=ctx.createRadialGradient(b.x-2,b.y-2,0,b.x,b.y,b.r);ballGrad.addColorStop(0,'#fff');ballGrad.addColorStop(1,'#FFD700');ctx.fillStyle=ballGrad;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();
d.particles=d.particles.filter(function(pt){pt.x+=pt.vx;pt.y+=pt.vy;pt.life--;ctx.globalAlpha=pt.life/12;ctx.fillStyle=pt.color;ctx.shadowColor=pt.color;ctx.shadowBlur=4;ctx.beginPath();ctx.arc(pt.x,pt.y,pt.size*(pt.life/12),0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;return pt.life>0;});ctx.globalAlpha=1;
if(d.bricks.every(function(br){return!br.alive;})){d.level++;d.score+=30;b.x=c.width/2;b.y=c.height-70;b.dx=5;b.dy=-5;spawnBreakoutBricks();}
ctx.fillStyle='#fff';ctx.font='bold 13px Poppins';ctx.textAlign='left';ctx.fillText('❤️ x'+d.lives+' | Lvl '+d.level+' | Combo: '+d.combo+' | Best: '+d.highScore,10,22);
gameAnimation=requestAnimationFrame(breakoutLoop);}
function spawnBParticles(x,y,color){for(var i=0;i<6;i++)breakoutData.particles.push({x:x,y:y,vx:(Math.random()-0.5)*5,vy:(Math.random()-0.5)*5-2,life:12,size:Math.random()*3+2,color:color});}
document.addEventListener('mousemove',function(e){if(breakoutData&&breakoutData.paddle&&gameCanvas){var r=gameCanvas.getBoundingClientRect();breakoutData.paddle.x=e.clientX-r.left-breakoutData.paddle.w/2;if(breakoutData.paddle.x<0)breakoutData.paddle.x=0;if(breakoutData.paddle.x+breakoutData.paddle.w>gameCanvas.width)breakoutData.paddle.x=gameCanvas.width-breakoutData.paddle.w;}});
document.addEventListener('touchmove',function(e){if(breakoutData&&breakoutData.paddle&&gameCanvas&&gameActive){var r=gameCanvas.getBoundingClientRect();breakoutData.paddle.x=e.touches[0].clientX-r.left-breakoutData.paddle.w/2;if(breakoutData.paddle.x<0)breakoutData.paddle.x=0;if(breakoutData.paddle.x+breakoutData.paddle.w>gameCanvas.width)breakoutData.paddle.x=gameCanvas.width-breakoutData.paddle.w;e.preventDefault();}},{passive:false});
