var flappyData;
function startFlappy(){openGameScreen('🐦 Flappy Bird');gameCanvas.style.display='block';flappyData={bird:{x:100,y:gameCanvas.height/2,r:18,vy:0,angle:0},pipes:[],score:0,bestScore:0,particles:[],clouds:[],frame:0,groundOffset:0,speed:2.5};flappyData.bestScore=parseInt(localStorage.getItem('flappyBest')||'0');for(var i=0;i<6;i++)flappyData.clouds.push({x:Math.random()*gameCanvas.width,y:Math.random()*gameCanvas.height*0.5,w:Math.random()*100+50,h:Math.random()*35+20,speed:Math.random()*0.4+0.2});currentGameRestart=startFlappy;gameAnimation=requestAnimationFrame(flappyLoop);}
function flappyLoop(){if(!gameActive)return;var c=gameCanvas,ctx=gameCtx,b=flappyData.bird,gs=flappyData.speed;flappyData.frame++;flappyData.groundOffset=(flappyData.groundOffset+gs)%40;
var sky=ctx.createLinearGradient(0,0,0,c.height);sky.addColorStop(0,'#1a3a5c');sky.addColorStop(0.4,'#2d5a87');sky.addColorStop(0.8,'#4a90d9');sky.addColorStop(1,'#87CEEB');ctx.fillStyle=sky;ctx.fillRect(0,0,c.width,c.height);
flappyData.clouds.forEach(function(cl){cl.x-=cl.speed;if(cl.x<-cl.w)cl.x=c.width+cl.w;ctx.fillStyle='rgba(255,255,255,0.2)';ctx.beginPath();ctx.ellipse(cl.x,cl.y,cl.w/2,cl.h/2,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(cl.x+cl.w*0.3,cl.y-cl.h*0.15,cl.w*0.35,cl.h*0.35,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(cl.x-cl.w*0.2,cl.y+cl.h*0.1,cl.w*0.25,cl.h*0.25,0,0,Math.PI*2);ctx.fill();});
b.vy+=0.6;b.y+=b.vy;b.angle=Math.min(Math.max(b.vy*0.08,-0.5),1.2);
if(flappyData.frame%80===0){var gap=155;flappyData.pipes.push({x:c.width,y:Math.random()*(c.height-gap-180)+90,gap:gap,scored:false});}
flappyData.pipes.forEach(function(p){p.x-=gs;});flappyData.pipes=flappyData.pipes.filter(function(p){return p.x>-80;});
flappyData.pipes.forEach(function(p){var pg=ctx.createLinearGradient(p.x,0,p.x+55,0);pg.addColorStop(0,'#2ED573');pg.addColorStop(0.5,'#7bed9f');pg.addColorStop(1,'#1e8e3e');ctx.fillStyle=pg;ctx.fillRect(p.x,0,55,p.y);ctx.fillStyle='#1e8e3e';ctx.fillRect(p.x-5,p.y-25,65,25);ctx.fillRect(p.x-3,p.y-32,61,10);ctx.fillStyle=pg;ctx.fillRect(p.x,p.y+p.gap,55,c.height);ctx.fillStyle='#1e8e3e';ctx.fillRect(p.x-5,p.y+p.gap,65,25);ctx.fillRect(p.x-3,p.y+p.gap+22,61,10);ctx.fillStyle='rgba(255,255,255,0.2)';ctx.fillRect(p.x+10,p.y-40,8,40);ctx.fillRect(p.x+10,p.y+p.gap,8,c.height);if(!p.scored&&p.x+55<b.x){p.scored=true;flappyData.score++;updateGameScore(flappyData.score);if(flappyData.score>flappyData.bestScore){flappyData.bestScore=flappyData.score;localStorage.setItem('flappyBest',flappyData.bestScore);}for(var i=0;i<8;i++)flappyData.particles.push({x:p.x,y:b.y,vx:-2,vy:(Math.random()-0.5)*3,life:15,color:'#FFD700'});}});
if(b.y-b.r<0||b.y+b.r>c.height-55){if(flappyData.score>flappyData.bestScore){flappyData.bestScore=flappyData.score;localStorage.setItem('flappyBest',flappyData.bestScore);}endGame('🐦 Score: '+flappyData.score+' | Best: '+flappyData.bestScore);return;}
flappyData.pipes.forEach(function(p){if(b.x+b.r>p.x&&b.x-b.r<p.x+55&&(b.y-b.r<p.y||b.y+b.r>p.y+p.gap)){if(flappyData.score>flappyData.bestScore){flappyData.bestScore=flappyData.score;localStorage.setItem('flappyBest',flappyData.bestScore);}endGame('🐦 Score: '+flappyData.score+' | Best: '+flappyData.bestScore);}});
ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.angle);var bodyGrad=ctx.createLinearGradient(0,-b.r,0,b.r);bodyGrad.addColorStop(0,'#FFD700');bodyGrad.addColorStop(0.5,'#FFA500');bodyGrad.addColorStop(1,'#FF8C00');ctx.fillStyle=bodyGrad;ctx.shadowColor='rgba(0,0,0,0.3)';ctx.shadowBlur=8;ctx.beginPath();ctx.arc(0,0,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#FFC107';ctx.beginPath();ctx.ellipse(-5,-5,13,9,-0.3,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(8,-4,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#000';ctx.beginPath();ctx.arc(10,-4,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(11,-5,1.8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#FF5722';ctx.beginPath();ctx.moveTo(16,2);ctx.lineTo(26,0);ctx.lineTo(16,-2);ctx.fill();ctx.fillStyle='#FF8C00';ctx.beginPath();ctx.moveTo(16,2);ctx.lineTo(22,1);ctx.lineTo(16,0);ctx.fill();ctx.restore();
var gg=ctx.createLinearGradient(0,c.height-55,0,c.height);gg.addColorStop(0,'#8B5E3C');gg.addColorStop(0.5,'#6B3A2A');gg.addColorStop(1,'#5D3A1A');ctx.fillStyle=gg;ctx.fillRect(0,c.height-55,c.width,55);ctx.fillStyle='#7A5230';for(var i=flappyData.groundOffset;i<c.width;i+=40)ctx.fillRect(i,c.height-52,20,6);ctx.strokeStyle='rgba(255,255,255,0.2)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,c.height-55);ctx.lineTo(c.width,c.height-55);ctx.stroke();
flappyData.particles=flappyData.particles.filter(function(pt){pt.x+=pt.vx;pt.y+=pt.vy;pt.life--;ctx.globalAlpha=pt.life/15;ctx.fillStyle=pt.color;ctx.beginPath();ctx.arc(pt.x,pt.y,3,0,Math.PI*2);ctx.fill();return pt.life>0;});ctx.globalAlpha=1;
ctx.fillStyle='rgba(255,255,255,0.7)';ctx.font='bold 14px Poppins';ctx.textAlign='right';ctx.fillText('Best: '+flappyData.bestScore,c.width-15,25);
gameAnimation=requestAnimationFrame(flappyLoop);}
document.addEventListener('click',function(e){if(flappyData&&flappyData.bird&&gameActive)flappyData.bird.vy=-9;});document.addEventListener('touchstart',function(e){if(flappyData&&flappyData.bird&&gameActive){flappyData.bird.vy=-9;e.preventDefault();}},{passive:false});document.addEventListener('keydown',function(e){if((e.key===' '||e.key==='ArrowUp')&&flappyData&&flappyData.bird&&gameActive){flappyData.bird.vy=-9;e.preventDefault();}});
