var invaderData;
function startInvaders(){openGameScreen('👾 Space Invaders');gameCanvas.style.display='block';invaderData={player:{x:gameCanvas.width/2,y:gameCanvas.height-60,w:55,h:28},enemies:[],bullets:[],enemyBullets:[],score:0,level:1,lives:3,shields:[],stars:[],frame:0,enemyDir:1,enemySpeed:1,particles:[],highScore:0};invaderData.highScore=parseInt(localStorage.getItem('invadersHigh')||'0');for(var i=0;i<80;i++)invaderData.stars.push({x:Math.random()*gameCanvas.width,y:Math.random()*gameCanvas.height,size:Math.random()*2.5+1,speed:Math.random()*0.4+0.1,twinkle:Math.random()*Math.PI*2});for(var i=0;i<4;i++)invaderData.shields.push({x:gameCanvas.width/5*(i+1)-35,y:gameCanvas.height-140,hp:15,maxHp:15});spawnInvaderWave();currentGameRestart=startInvaders;gameAnimation=requestAnimationFrame(invaderLoop);}
function spawnInvaderWave(){invaderData.enemies=[];var types=[{color:'#FF4757',points:30,emoji:'👾'},{color:'#FF6B81',points:20,emoji:'👽'},{color:'#FFA502',points:15,emoji:'🤖'},{color:'#7C3AED',points:10,emoji:'🛸'}];for(var r=0;r<5;r++)for(var c=0;c<8;c++)invaderData.enemies.push({x:c*50+40,y:r*40+50,w:35,h:28,alive:true,type:types[Math.min(r,3)],bob:Math.random()*Math.PI*2});invaderData.enemySpeed=1+invaderData.level*0.4;}
function invaderLoop(){if(!gameActive)return;var c=gameCanvas,ctx=gameCtx,p=invaderData.player,d=invaderData;d.frame++;
var bgGrad=ctx.createLinearGradient(0,0,0,c.height);bgGrad.addColorStop(0,'#0A0E27');bgGrad.addColorStop(1,'#1a1040');ctx.fillStyle=bgGrad;ctx.fillRect(0,0,c.width,c.height);
d.stars.forEach(function(s){s.y+=s.speed;if(s.y>c.height){s.y=0;s.x=Math.random()*c.width;}var twinkle=Math.sin(d.frame*0.03+s.twinkle)*0.5+0.5;ctx.fillStyle='rgba(255,255,255,'+(0.3+twinkle*0.5)+')';ctx.beginPath();ctx.arc(s.x,s.y,s.size,0,Math.PI*2);ctx.fill();});
var hitEdge=false;d.enemies.forEach(function(e){if(!e.alive)return;e.x+=d.enemyDir*d.enemySpeed;e.y+=Math.sin(d.frame*0.04+e.bob)*0.4;if(e.x<=15||e.x>=c.width-50)hitEdge=true;if(e.y>c.height-120)endGame('👾 Invaders Win! Score: '+d.score);
var eg=ctx.createLinearGradient(e.x,e.y,e.x,e.y+e.h);eg.addColorStop(0,e.type.color);eg.addColorStop(1,'rgba(0,0,0,0.4)');ctx.fillStyle=eg;ctx.shadowColor=e.type.color;ctx.shadowBlur=10;ctx.beginPath();ctx.roundRect(e.x,e.y,e.w,e.h,6);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='rgba(255,255,255,0.2)';ctx.fillRect(e.x,e.y,e.w,6);ctx.fillStyle='#fff';ctx.font='18px Arial';ctx.textAlign='center';ctx.fillText(e.type.emoji,e.x+e.w/2,e.y+20);});
if(hitEdge){d.enemyDir*=-1;d.enemies.forEach(function(e){e.y+=15;});}
if(Math.random()<0.02+d.level*0.008){var alive=d.enemies.filter(function(e){return e.alive;});if(alive.length>0){var s=alive[Math.floor(Math.random()*alive.length)];d.enemyBullets.push({x:s.x+s.w/2,y:s.y+s.h,vy:4+d.level,color:'#FF4757'});}}
d.enemyBullets.forEach(function(b){b.y+=b.vy;var bglow=ctx.createRadialGradient(b.x,b.y,0,b.x,b.y,6);bglow.addColorStop(0,b.color);bglow.addColorStop(1,'rgba(255,71,87,0)');ctx.fillStyle=bglow;ctx.beginPath();ctx.arc(b.x,b.y,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(b.x,b.y,2,0,Math.PI*2);ctx.fill();});d.enemyBullets=d.enemyBullets.filter(function(b){return b.y<c.height;});
d.bullets.forEach(function(b){b.y-=9;var bglow=ctx.createRadialGradient(b.x,b.y,0,b.x,b.y,5);bglow.addColorStop(0,'#00D4FF');bglow.addColorStop(1,'rgba(0,212,255,0)');ctx.fillStyle=bglow;ctx.beginPath();ctx.arc(b.x,b.y,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(b.x,b.y,2,0,Math.PI*2);ctx.fill();d.enemies.forEach(function(e){if(e.alive&&b.x>e.x&&b.x<e.x+e.w&&b.y>e.y&&b.y<e.y+e.h){e.alive=false;b.y=-10;d.score+=e.type.points;updateGameScore(d.score);for(var i=0;i<8;i++)d.particles.push({x:e.x+e.w/2,y:e.y+e.h/2,vx:(Math.random()-0.5)*4,vy:(Math.random()-0.5)*4,life:12,color:e.type.color,size:Math.random()*3+2});}});});d.bullets=d.bullets.filter(function(b){return b.y>0;});
d.enemyBullets.forEach(function(b){if(b.x>p.x&&b.x<p.x+p.w&&b.y>p.y&&b.y<p.y+p.h){d.lives--;b.y=c.height+10;for(var i=0;i<6;i++)d.particles.push({x:p.x+p.w/2,y:p.y+p.h/2,vx:(Math.random()-0.5)*5,vy:(Math.random()-0.5)*5,life:10,color:'#FF4757',size:Math.random()*3+2});if(d.lives<=0){if(d.score>d.highScore){d.highScore=d.score;localStorage.setItem('invadersHigh',d.highScore);}endGame('👾 Game Over! Score: '+d.score+' | Best: '+d.highScore);}}});
d.shields.forEach(function(s){if(s.hp>0){var alpha=s.hp/s.maxHp;ctx.fillStyle='rgba(0,212,255,'+(alpha*0.4)+')';ctx.fillRect(s.x,s.y,70,22);ctx.strokeStyle='rgba(0,212,255,'+(alpha*0.8)+')';ctx.lineWidth=2;ctx.strokeRect(s.x,s.y,70,22);ctx.fillStyle='rgba(255,255,255,'+(alpha*0.2)+')';ctx.fillRect(s.x,s.y,70,5);}});
var pg=ctx.createLinearGradient(p.x,p.y,p.x,p.y+p.h);pg.addColorStop(0,'#00D4FF');pg.addColorStop(1,'#0088cc');ctx.fillStyle=pg;ctx.shadowColor='#00D4FF';ctx.shadowBlur=20;ctx.beginPath();ctx.moveTo(p.x+p.w/2,p.y-5);ctx.lineTo(p.x-5,p.y+p.h);ctx.lineTo(p.x+p.w+5,p.y+p.h);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(p.x+p.w/2,p.y+5,6,0,Math.PI*2);ctx.fill();
d.particles=d.particles.filter(function(pt){pt.x+=pt.vx;pt.y+=pt.vy;pt.life--;ctx.globalAlpha=pt.life/12;ctx.fillStyle=pt.color;ctx.shadowColor=pt.color;ctx.shadowBlur=4;ctx.beginPath();ctx.arc(pt.x,pt.y,pt.size*(pt.life/12),0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;return pt.life>0;});ctx.globalAlpha=1;
ctx.fillStyle='#fff';ctx.font='bold 13px Poppins';ctx.textAlign='left';ctx.fillText('❤️ x'+d.lives+' | Lvl '+d.level+' | Best: '+d.highScore,10,22);
if(d.enemies.every(function(e){return!e.alive;})){d.level++;d.score+=50;spawnInvaderWave();}
gameAnimation=requestAnimationFrame(invaderLoop);}
document.addEventListener('mousemove',function(e){if(invaderData&&invaderData.player&&gameCanvas){var r=gameCanvas.getBoundingClientRect();invaderData.player.x=e.clientX-r.left-27;}});document.addEventListener('touchmove',function(e){if(invaderData&&invaderData.player&&gameCanvas&&gameActive){var r=gameCanvas.getBoundingClientRect();invaderData.player.x=e.touches[0].clientX-r.left-27;invaderData.bullets.push({x:invaderData.player.x+27,y:invaderData.player.y});e.preventDefault();}},{passive:false});document.addEventListener('click',function(e){if(invaderData&&invaderData.player&&gameActive)invaderData.bullets.push({x:invaderData.player.x+27,y:invaderData.player.y});});
