var racingData;
function startRacing(){openGameScreen('🏎️ Racing');gameCanvas.style.display='block';gameCanvas.width=Math.min(window.innerWidth,400);gameCanvas.height=Math.min(window.innerHeight-100,500);racingData={player:{x:gameCanvas.width/2-20,y:gameCanvas.height-100,w:40,h:70},obstacles:[],coins:[],road:{offset:0,lines:[]},score:0,speed:4,frame:0,highScore:parseInt(localStorage.getItem('racingHigh')||'0'),lives:3};for(var i=0;i<6;i++)racingData.road.lines.push({x:gameCanvas.width/2-2,y:(i*80+racingData.road.offset)%480});currentGameRestart=startRacing;gameAnimation=requestAnimationFrame(racingLoop);}
function racingLoop(){if(!gameActive)return;var c=gameCanvas,ctx=gameCtx,d=racingData;d.frame++;d.road.offset=(d.road.offset+d.speed)%80;var bgGrad=ctx.createLinearGradient(0,0,0,c.height);bgGrad.addColorStop(0,'#1a1a2e');bgGrad.addColorStop(1,'#0A0E27');ctx.fillStyle=bgGrad;ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#333';ctx.fillRect(c.width/2-60,0,120,c.height);ctx.fillStyle='#444';ctx.fillRect(c.width/2-55,0,110,c.height);ctx.strokeStyle='#fff';ctx.setLineDash([30,20]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(c.width/2,0);ctx.lineTo(c.width/2,c.height);ctx.stroke();ctx.setLineDash([]);d.road.lines.forEach(function(l){ctx.fillStyle='#fff';ctx.fillRect(l.x,l.y,4,40);});d.road.lines.forEach(function(l){l.y=(l.y+d.speed)%480;});if(d.frame%50===0){var ox=Math.random()<0.5?c.width/2-50:c.width/2+20;d.obstacles.push({x:ox,y:-70,w:40,h:60});}if(d.frame%40===0){var cx=c.width/2-55+Math.random()*110;d.coins.push({x:cx,y:-20,r:10});}d.obstacles.forEach(function(o){o.y+=d.speed;});d.obstacles=d.obstacles.filter(function(o){return o.y<c.height+100;});d.coins.forEach(function(c){c.y+=d.speed;});d.coins=d.coins.filter(function(c){return c.y<c.height+50;});
d.obstacles.forEach(function(o){var grad=ctx.createLinearGradient(o.x,o.y,o.x+o.w,o.y);grad.addColorStop(0,'#FF4757');grad.addColorStop(1,'#c0392b');ctx.fillStyle=grad;ctx.fillRect(o.x,o.y,o.w,o.h);ctx.fillStyle='#333';ctx.fillRect(o.x+5,o.y+10,10,15);ctx.fillRect(o.x+o.w-15,o.y+10,10,15);ctx.fillStyle='rgba(255,255,255,0.3)';ctx.fillRect(o.x,o.y,o.w,5);if(d.player.x<o.x+o.w&&d.player.x+d.player.w>o.x&&d.player.y<o.y+o.h&&d.player.y+d.player.h>o.y){d.lives--;o.y=c.height+200;if(d.lives<=0){if(d.score>d.highScore){d.highScore=Math.floor(d.score);localStorage.setItem('racingHigh',d.highScore);}endGame('🏎️ Score: '+Math.floor(d.score)+' | Best: '+d.highScore);return;}}});
d.coins.forEach(function(c){var coinGlow=ctx.createRadialGradient(c.x,c.y,0,c.x,c.y,c.r*1.5);coinGlow.addColorStop(0,'rgba(255,215,0,0.4)');coinGlow.addColorStop(1,'rgba(255,215,0,0)');ctx.fillStyle=coinGlow;ctx.beginPath();ctx.arc(c.x,c.y,c.r*1.5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#FFD700';ctx.beginPath();ctx.arc(c.x,c.y,c.r,0,Math.PI*2);ctx.fill();if(Math.hypot(d.player.x+d.player.w/2-c.x,d.player.y+d.player.h/2-c.y)<35){c.y=c.height+100;d.score+=20;updateGameScore(Math.floor(d.score));}});
var pg=ctx.createLinearGradient(d.player.x,d.player.y,d.player.x+d.player.w,d.player.y);pg.addColorStop(0,'#D4AF37');pg.addColorStop(0.5,'#F5E6A3');pg.addColorStop(1,'#B8941F');ctx.fillStyle=pg;ctx.shadowColor='#D4AF37';ctx.shadowBlur=12;ctx.beginPath();ctx.roundRect(d.player.x,d.player.y,d.player.w,d.player.h,8);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#00D4FF';ctx.fillRect(d.player.x+5,d.player.y+5,12,15);ctx.fillRect(d.player.x+d.player.w-17,d.player.y+5,12,15);ctx.fillStyle='#000';ctx.fillRect(d.player.x+8,d.player.y+8,6,9);ctx.fillRect(d.player.x+d.player.w-14,d.player.y+8,6,9);
d.score+=0.2;updateGameScore(Math.floor(d.score));if(d.frame%300===0)d.speed+=0.3;ctx.fillStyle='#fff';ctx.font='bold 13px Poppins';ctx.textAlign='left';ctx.fillText('❤️ x'+d.lives+' | Best: '+d.highScore,10,22);
gameAnimation=requestAnimationFrame(racingLoop);}
document.addEventListener('mousemove',function(e){if(racingData&&racingData.player&&gameCanvas){var r=gameCanvas.getBoundingClientRect();racingData.player.x=e.clientX-r.left-racingData.player.w/2;}});document.addEventListener('touchmove',function(e){if(racingData&&racingData.player&&gameCanvas&&gameActive){var r=gameCanvas.getBoundingClientRect();racingData.player.x=e.touches[0].clientX-r.left-racingData.player.w/2;e.preventDefault();}},{passive:false});
