var runnerData;
function startRunner(){openGameScreen('🏃 Runner');gameCanvas.style.display='block';runnerData={player:{x:70,y:0,w:32,h:55,vy:0,jumping:false,doubleJump:false},ground:0,obstacles:[],coins:[],score:0,speed:6,frame:0,particles:[],bgMountains:[],bgBuildings:[],highScore:0};runnerData.player.y=gameCanvas.height-100;runnerData.ground=gameCanvas.height-45;runnerData.highScore=parseInt(localStorage.getItem('runnerHigh')||'0');for(var i=0;i<10;i++){runnerData.bgMountains.push({x:i*150,height:Math.random()*70+40,color:'#1a1040'});runnerData.bgBuildings.push({x:i*200,height:Math.random()*60+30,width:Math.random()*40+30,color:'#'+Math.floor(Math.random()*16777215).toString(16)});}currentGameRestart=startRunner;gameAnimation=requestAnimationFrame(runnerLoop);}
function runnerLoop(){if(!gameActive)return;var c=gameCanvas,ctx=gameCtx,p=runnerData.player,g=runnerData.ground,d=runnerData;d.frame++;
var sky=ctx.createLinearGradient(0,0,0,c.height);sky.addColorStop(0,'#1a1a3e');sky.addColorStop(0.4,'#2d1b69');sky.addColorStop(0.8,'#1a1040');sky.addColorStop(1,'#0A0E27');ctx.fillStyle=sky;ctx.fillRect(0,0,c.width,c.height);
ctx.fillStyle='rgba(255,255,255,0.2)';for(var i=0;i<30;i++){var sx=(i*97+d.frame*0.3)%c.width;var sy=(i*43)%(g-50);var twinkle=Math.sin(d.frame*0.02+i)*0.5+0.5;ctx.fillStyle='rgba(255,255,255,'+(0.2+twinkle*0.3)+')';ctx.beginPath();ctx.arc(sx,sy,1.5,0,Math.PI*2);ctx.fill();}
d.bgMountains.forEach(function(m){m.x-=1.5;if(m.x<-150)m.x=c.width+150;ctx.fillStyle=m.color;ctx.beginPath();ctx.moveTo(m.x,g);ctx.lineTo(m.x+75,g-m.height);ctx.lineTo(m.x+150,g);ctx.fill();});
d.bgBuildings.forEach(function(b){b.x-=2;if(b.x<-100)b.x=c.width+100;ctx.fillStyle='rgba(26,16,64,0.6)';ctx.fillRect(b.x,g-b.height,b.width,b.height);ctx.fillStyle='rgba(255,215,0,0.3)';for(var wy=b.x+5;wy<b.x+b.width-5;wy+=12){for(var wx=g-b.height+5;wx<g-5;wx+=12){if(Math.random()<0.3)ctx.fillRect(wy,wx,6,6);}}});
var gg=ctx.createLinearGradient(0,g,0,g+45);gg.addColorStop(0,'#2d1b69');gg.addColorStop(0.3,'#1a1040');gg.addColorStop(1,'#0A0E27');ctx.fillStyle=gg;ctx.fillRect(0,g,c.width,45);ctx.strokeStyle='rgba(212,175,55,0.4)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,g);ctx.lineTo(c.width,g);ctx.stroke();ctx.fillStyle='rgba(212,175,55,0.1)';for(var i=(d.frame*2)%40;i<c.width;i+=40)ctx.fillRect(i,g,20,3);
if(p.jumping){p.vy+=0.8;p.y+=p.vy;if(p.y>=g-p.h){p.y=g-p.h;p.jumping=false;p.doubleJump=false;p.vy=0;for(var i=0;i<8;i++)spawnRParticles(p.x+p.w/2,p.y+p.h,'#D4AF37');}}
if(d.frame%55===0)d.obstacles.push({x:c.width,y:g-32,w:22,h:32,type:'spike'});if(d.frame%90===0)d.obstacles.push({x:c.width,y:g-48,w:28,h:48,type:'block'});if(d.frame%120===0)d.coins.push({x:c.width,y:g-85,r:11,collected:false,bob:Math.random()*Math.PI*2});
d.obstacles.forEach(function(o){o.x-=d.speed;});d.obstacles=d.obstacles.filter(function(o){return o.x>-50;});d.coins.forEach(function(c){c.x-=d.speed;});d.coins=d.coins.filter(function(c){return c.x>-30;});
d.obstacles.forEach(function(o){if(o.type==='spike'){var sg=ctx.createLinearGradient(o.x,o.y+o.h,o.x+o.w/2,o.y);sg.addColorStop(0,'#FF4757');sg.addColorStop(1,'#FF6B81');ctx.fillStyle=sg;ctx.shadowColor='#FF4757';ctx.shadowBlur=10;ctx.beginPath();ctx.moveTo(o.x,o.y+o.h);ctx.lineTo(o.x+o.w/2,o.y);ctx.lineTo(o.x+o.w,o.y+o.h);ctx.closePath();ctx.fill();ctx.shadowBlur=0;}else{var bg2=ctx.createLinearGradient(o.x,o.y,o.x+o.w,o.y+o.h);bg2.addColorStop(0,'#FF4757');bg2.addColorStop(0.5,'#FF6B81');bg2.addColorStop(1,'#c0392b');ctx.fillStyle=bg2;ctx.fillRect(o.x,o.y,o.w,o.h);ctx.fillStyle='rgba(0,0,0,0.3)';ctx.fillRect(o.x,o.y,o.w,6);ctx.fillStyle='rgba(255,255,255,0.1)';ctx.fillRect(o.x+4,o.y+8,6,25);}});
d.coins.forEach(function(c){if(!c.collected){var pulse=Math.sin(d.frame*0.08+c.bob)*0.15+0.85;var coinGlow=ctx.createRadialGradient(c.x,c.y,0,c.x,c.y,c.r*2);coinGlow.addColorStop(0,'rgba(255,215,0,0.4)');coinGlow.addColorStop(1,'rgba(255,215,0,0)');ctx.fillStyle=coinGlow;ctx.beginPath();ctx.arc(c.x,c.y,c.r*2,0,Math.PI*2);ctx.fill();var coinGrad=ctx.createRadialGradient(c.x-2,c.y-2,0,c.x,c.y,c.r);coinGrad.addColorStop(0,'#FFD700');coinGrad.addColorStop(1,'#DAA520');ctx.fillStyle=coinGrad;ctx.shadowColor='#FFD700';ctx.shadowBlur=8;ctx.beginPath();ctx.arc(c.x,c.y,c.r*pulse,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#FFF8DC';ctx.beginPath();ctx.arc(c.x-3,c.y-3,c.r*0.3,0,Math.PI*2);ctx.fill();}});
d.obstacles.forEach(function(o){if(p.x+p.w>o.x&&p.x<o.x+o.w&&p.y+p.h>o.y){if(d.score>d.highScore){d.highScore=Math.floor(d.score);localStorage.setItem('runnerHigh',d.highScore);}endGame('🏃 Score: '+Math.floor(d.score)+' | Best: '+d.highScore);}});
d.coins.forEach(function(c){if(!c.collected&&Math.hypot(p.x+p.w/2-c.x,p.y+p.h/2-c.y)<28){c.collected=true;d.score+=50;updateGameScore(Math.floor(d.score));for(var i=0;i<10;i++)spawnRParticles(c.x,c.y,'#FFD700');}});
var pg=ctx.createLinearGradient(p.x,p.y,p.x,p.y+p.h);pg.addColorStop(0,'#D4AF37');pg.addColorStop(0.5,'#F5E6A3');pg.addColorStop(1,'#B8941F');ctx.fillStyle=pg;ctx.shadowColor='#D4AF37';ctx.shadowBlur=12;ctx.beginPath();ctx.roundRect(p.x,p.y,p.w,p.h,7);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#F5E6A3';ctx.shadowColor='#000';ctx.shadowBlur=4;ctx.beginPath();ctx.arc(p.x+p.w/2,p.y+9,11,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#000';ctx.beginPath();ctx.arc(p.x+p.w/2+4,p.y+6,2.5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#FF4757';ctx.beginPath();ctx.arc(p.x+p.w/2-5,p.y+13,4,0,Math.PI*2);ctx.fill();
d.particles=d.particles.filter(function(pt){pt.x+=pt.vx;pt.y+=pt.vy;pt.life--;ctx.globalAlpha=pt.life/15;ctx.fillStyle=pt.color;ctx.shadowColor=pt.color;ctx.shadowBlur=4;ctx.beginPath();ctx.arc(pt.x,pt.y,pt.size*(pt.life/15),0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;return pt.life>0;});ctx.globalAlpha=1;
d.score+=0.3;updateGameScore(Math.floor(d.score));if(d.frame%250===0)d.speed+=0.4;
ctx.fillStyle='rgba(255,255,255,0.6)';ctx.font='bold 13px Poppins';ctx.textAlign='right';ctx.fillText('Best: '+d.highScore,c.width-15,25);
gameAnimation=requestAnimationFrame(runnerLoop);}
function spawnRParticles(x,y,color){for(var i=0;i<6;i++)runnerData.particles.push({x:x,y:y,vx:(Math.random()-0.5)*4,vy:(Math.random()-0.5)*4-3,life:15,size:Math.random()*3+2,color:color});}
function runnerJump(){var p=runnerData&&runnerData.player;if(!p||!gameActive)return;if(!p.jumping){p.jumping=true;p.vy=-14;}else if(!p.doubleJump){p.doubleJump=true;p.vy=-11;}}
document.addEventListener('touchstart',function(e){runnerJump();e.preventDefault();},{passive:false});document.addEventListener('click',runnerJump);document.addEventListener('keydown',function(e){if((e.key===' '||e.key==='ArrowUp')&&runnerData&&runnerData.player&&gameActive){if(!runnerData.player.jumping){runnerData.player.jumping=true;runnerData.player.vy=-14;e.preventDefault();}}});
