var towerData;
function startTowerDefense(){openGameScreen('🏰 Tower Defense');gameCanvas.style.display='block';towerData={towers:[],enemies:[],bullets:[],gold:250,lives:20,score:0,wave:1,frame:0,path:[{x:0,y:180},{x:180,y:180},{x:180,y:320},{x:360,y:320},{x:360,y:180},{x:540,y:180},{x:540,y:320},{x:720,y:320},{x:720,y:250},{x:900,y:250}],highScore:0,particles:[]};towerData.highScore=parseInt(localStorage.getItem('towerHigh')||'0');currentGameRestart=startTowerDefense;if(towerClickHandler)document.removeEventListener('click',towerClickHandler);towerClickHandler=function(e){if(!gameActive||!towerData||!gameCanvas)return;if(towerData.gold<100){showToast('Need 100 gold!','error');return;}var r=gameCanvas.getBoundingClientRect();var x=e.clientX-r.left,y=e.clientY-r.top;if(x>=0&&x<=gameCanvas.width&&y>=0&&y<=gameCanvas.height){towerData.towers.push({x:x,y:y,level:1});towerData.gold-=100;}};document.addEventListener('click',towerClickHandler);gameAnimation=requestAnimationFrame(towerLoop);spawnTowerWave();}
function spawnTowerWave(){for(var i=0;i<5+towerData.wave*3;i++){setTimeout(function(){if(!gameActive)return;towerData.enemies.push({x:towerData.path[0].x,y:towerData.path[0].y,pathIndex:0,hp:3+towerData.wave,speed:1.2+towerData.wave*0.3,maxHp:3+towerData.wave,gold:12+towerData.wave*3,size:15});},i*250);}}
function towerLoop(){if(!gameActive)return;var c=gameCanvas,ctx=gameCtx,d=towerData;d.frame++;
var bgGrad=ctx.createLinearGradient(0,0,0,c.height);bgGrad.addColorStop(0,'#1a2a1a');bgGrad.addColorStop(1,'#0A0E27');ctx.fillStyle=bgGrad;ctx.fillRect(0,0,c.width,c.height);
ctx.strokeStyle='#4A3728';ctx.lineWidth=42;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(d.path[0].x,d.path[0].y);for(var i=1;i<d.path.length;i++)ctx.lineTo(d.path[i].x,d.path[i].y);ctx.stroke();ctx.strokeStyle='#6B5B3A';ctx.lineWidth=34;ctx.stroke();ctx.strokeStyle='#8B7355';ctx.lineWidth=26;ctx.setLineDash([15,20]);ctx.stroke();ctx.setLineDash([]);
d.enemies.forEach(function(e){if(e.pathIndex<d.path.length-1){var t=d.path[e.pathIndex+1],dx=t.x-e.x,dy=t.y-e.y,dist=Math.hypot(dx,dy);if(dist<e.speed){e.pathIndex++;e.x=t.x;e.y=t.y;}else{e.x+=(dx/dist)*e.speed;e.y+=(dy/dist)*e.speed;}}else{d.lives--;e.hp=0;for(var i=0;i<8;i++)d.particles.push({x:e.x,y:e.y,vx:(Math.random()-0.5)*3,vy:(Math.random()-0.5)*3,life:10,color:'#FF4757'});if(d.lives<=0){if(d.score>d.highScore){d.highScore=d.score;localStorage.setItem('towerHigh',d.highScore);}endGame('🏰 Defeated! Wave: '+d.wave+' | Score: '+d.score+' | Best: '+d.highScore);}}
if(e.hp>0){var eg=ctx.createRadialGradient(e.x,e.y,0,e.x,e.y,e.size);eg.addColorStop(0,'#FF4757');eg.addColorStop(1,'rgba(255,71,87,0)');ctx.fillStyle=eg;ctx.beginPath();ctx.arc(e.x,e.y,e.size*1.8,0,Math.PI*2);ctx.fill();var enemyGrad=ctx.createRadialGradient(e.x-2,e.y-2,0,e.x,e.y,e.size);enemyGrad.addColorStop(0,'#FF6B81');enemyGrad.addColorStop(1,'#c0392b');ctx.fillStyle=enemyGrad;ctx.beginPath();ctx.arc(e.x,e.y,e.size,0,Math.PI*2);ctx.fill();ctx.fillStyle='#000';ctx.beginPath();ctx.arc(e.x-5,e.y-3,3.5,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(e.x+5,e.y-3,3.5,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(0,0,0,0.5)';ctx.fillRect(e.x-14,e.y-20,28,4);var hpRatio=e.hp/e.maxHp;var hpColor=hpRatio>0.5?'#2ED573':hpRatio>0.25?'#FFA502':'#FF4757';ctx.fillStyle=hpColor;ctx.fillRect(e.x-14,e.y-20,28*hpRatio,4);}}});d.enemies=d.enemies.filter(function(e){return e.hp>0;});
d.towers.forEach(function(t){var target=null,minDist=140;d.enemies.forEach(function(e){var dist=Math.hypot(t.x-e.x,t.y-e.y);if(dist<minDist){minDist=dist;target=e;}});if(target&&d.frame%12===0)d.bullets.push({x:t.x,y:t.y,target:target,speed:8,damage:t.level});var tg=ctx.createLinearGradient(t.x-18,t.y-18,t.x+18,t.y+18);tg.addColorStop(0,'#D4AF37');tg.addColorStop(1,'#8B6914');ctx.fillStyle=tg;ctx.shadowColor='#D4AF37';ctx.shadowBlur=12;ctx.fillRect(t.x-18,t.y-18,36,36);ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.font='24px Arial';ctx.textAlign='center';ctx.fillText('🏰',t.x,t.y+8);ctx.fillStyle='#fff';ctx.font='bold 10px Poppins';ctx.fillText('Lv.'+t.level,t.x,t.y-20);});
d.bullets.forEach(function(b){if(b.target.hp>0){var dx=b.target.x-b.x,dy=b.target.y-b.y,dist=Math.hypot(dx,dy);b.x+=(dx/dist)*b.speed;b.y+=(dy/dist)*b.speed;if(dist<15){b.target.hp-=b.damage;b.hit=true;if(b.target.hp<=0){d.gold+=b.target.gold;d.score+=b.target.gold;updateGameScore(d.score);for(var i=0;i<10;i++)d.particles.push({x:b.target.x,y:b.target.y,vx:(Math.random()-0.5)*4,vy:(Math.random()-0.5)*4-2,life:12,color:'#FFD700'});}}}var bulletGlow=ctx.createRadialGradient(b.x,b.y,0,b.x,b.y,6);bulletGlow.addColorStop(0,'#FFD700');bulletGlow.addColorStop(1,'rgba(255,215,0,0)');ctx.fillStyle=bulletGlow;ctx.beginPath();ctx.arc(b.x,b.y,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(b.x,b.y,2.5,0,Math.PI*2);ctx.fill();});d.bullets=d.bullets.filter(function(b){return!b.hit;});
d.particles=d.particles.filter(function(pt){pt.x+=pt.vx;pt.y+=pt.vy;pt.life--;ctx.globalAlpha=pt.life/12;ctx.fillStyle=pt.color;ctx.beginPath();ctx.arc(pt.x,pt.y,3*(pt.life/12),0,Math.PI*2);ctx.fill();return pt.life>0;});ctx.globalAlpha=1;
if(d.enemies.length===0){d.wave++;d.gold+=80;spawnTowerWave();}
ctx.fillStyle='#fff';ctx.font='bold 14px Poppins';ctx.textAlign='left';ctx.fillText('❤️ '+d.lives+' | 💰 '+d.gold+' | 🌊 Wave '+d.wave+' | Best: '+d.highScore,10,22);ctx.fillText('Tap to place tower (100💰)',10,c.height-10);
gameAnimation=requestAnimationFrame(towerLoop);}
