var trafficData;
function startTraffic(){openGameScreen('🚦 Traffic Control');gameCanvas.style.display='block';gameCanvas.width=Math.min(window.innerWidth,400);gameCanvas.height=Math.min(window.innerHeight-100,600);trafficData={cars:[],player:{x:gameCanvas.width/2-25,y:gameCanvas.height-80,w:50,h:80},score:0,lives:3,frame:0,speed:3,highScore:parseInt(localStorage.getItem('trafficHigh')||'0'),particles:[]};currentGameRestart=startTraffic;gameAnimation=requestAnimationFrame(trafficLoop);}
function trafficLoop(){if(!gameActive)return;var c=gameCanvas,ctx=gameCtx,d=trafficData;d.frame++;var bgGrad=ctx.createLinearGradient(0,0,0,c.height);bgGrad.addColorStop(0,'#1a1a2e');bgGrad.addColorStop(1,'#0A0E27');ctx.fillStyle=bgGrad;ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#333';ctx.fillRect(c.width/2-65,0,130,c.height);ctx.fillStyle='#444';ctx.fillRect(c.width/2-60,0,120,c.height);ctx.strokeStyle='#fff';ctx.setLineDash([25,20]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(c.width/4,0);ctx.lineTo(c.width/4,c.height);ctx.stroke();ctx.beginPath();ctx.moveTo(c.width*3/4,0);ctx.lineTo(c.width*3/4,c.height);ctx.stroke();ctx.setLineDash([]);
if(d.frame%40===0){var lane=Math.floor(Math.random()*4);var cx;if(lane===0)cx=c.width/4-35;else if(lane===1)cx=c.width/4+10;else if(lane===2)cx=c.width*3/4-35;else cx=c.width*3/4+10;d.cars.push({x:cx,y:-80,w:45,h:75,lane:lane,speed:d.speed+Math.random()*2,color:['#FF4757','#2ED573','#FFD700','#00D4FF','#FFA502','#7C3AED'][Math.floor(Math.random()*6)]});}
d.cars.forEach(function(car){car.y+=car.speed;});d.cars=d.cars.filter(function(car){return car.y<c.height+100;});
d.cars.forEach(function(car){var grad=ctx.createLinearGradient(car.x,car.y,car.x,car.y+car.h);grad.addColorStop(0,car.color);grad.addColorStop(1,'rgba(0,0,0,0.3)');ctx.fillStyle=grad;ctx.shadowColor=car.color;ctx.shadowBlur=8;ctx.beginPath();ctx.roundRect(car.x,car.y,car.w,car.h,10);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#333';ctx.fillRect(car.x+5,car.y+10,15,18);ctx.fillRect(car.x+car.w-20,car.y+10,15,18);ctx.fillStyle='rgba(255,255,255,0.3)';ctx.fillRect(car.x+5,car.y+35,15,10);ctx.fillRect(car.x+car.w-20,car.y+35,15,10);ctx.fillStyle='rgba(255,255,255,0.6)';ctx.fillRect(car.x+8,car.y+8,8,12);ctx.fillRect(car.x+car.w-16,car.y+8,8,12);
if(d.player.x<car.x+car.w&&d.player.x+d.player.w>car.x&&d.player.y<car.y+car.h&&d.player.y+d.player.h>car.y){d.lives--;car.y=c.height+200;for(var i=0;i<10;i++)d.particles.push({x:d.player.x+d.player.w/2,y:d.player.y+d.player.h/2,vx:(Math.random()-0.5)*5,vy:(Math.random()-0.5)*5,life:12,color:'#FF4757'});if(d.lives<=0){if(d.score>d.highScore){d.highScore=Math.floor(d.score);localStorage.setItem('trafficHigh',d.highScore);}endGame('🚦 Score: '+Math.floor(d.score)+' | Best: '+d.highScore);return;}}});
var pg=ctx.createLinearGradient(d.player.x,d.player.y,d.player.x,d.player.y+d.player.h);pg.addColorStop(0,'#D4AF37');pg.addColorStop(0.5,'#F5E6A3');pg.addColorStop(1,'#B8941F');ctx.fillStyle=pg;ctx.shadowColor='#D4AF37';ctx.shadowBlur=15;ctx.beginPath();ctx.roundRect(d.player.x,d.player.y,d.player.w,d.player.h,12);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#00D4FF';ctx.fillRect(d.player.x+5,d.player.y+5,15,20);ctx.fillRect(d.player.x+d.player.w-20,d.player.y+5,15,20);ctx.fillStyle='rgba(0,0,0,0.5)';ctx.fillRect(d.player.x+8,d.player.y+8,9,14);ctx.fillRect(d.player.x+d.player.w-17,d.player.y+8,9,14);ctx.fillStyle='rgba(255,255,255,0.5)';ctx.fillRect(d.player.x+10,d.player.y+35,10,8);ctx.fillRect(d.player.x+d.player.w-20,d.player.y+35,10,8);
d.particles=d.particles.filter(function(pt){pt.x+=pt.vx;pt.y+=pt.vy;pt.life--;ctx.globalAlpha=pt.life/12;ctx.fillStyle=pt.color;ctx.beginPath();ctx.arc(pt.x,pt.y,3*(pt.life/12),0,Math.PI*2);ctx.fill();return pt.life>0;});ctx.globalAlpha=1;
d.score+=0.5;updateGameScore(Math.floor(d.score));if(d.frame%400===0)d.speed+=0.5;
ctx.fillStyle='#fff';ctx.font='bold 14px Poppins';ctx.textAlign='left';ctx.fillText('❤️ x'+d.lives+' | Speed: '+Math.floor(d.speed*10)+' | Best: '+d.highScore,10,22);
gameAnimation=requestAnimationFrame(trafficLoop);}
document.addEventListener('mousemove',function(e){if(trafficData&&trafficData.player&&gameCanvas){var r=gameCanvas.getBoundingClientRect();trafficData.player.x=e.clientX-r.left-trafficData.player.w/2;}});document.addEventListener('touchmove',function(e){if(trafficData&&trafficData.player&&gameCanvas&&gameActive){var r=gameCanvas.getBoundingClientRect();trafficData.player.x=e.touches[0].clientX-r.left-trafficData.player.w/2;e.preventDefault();}},{passive:false});
